### ISSUE TITLE
Bug: cannot use `0` as non-plural translation arguments

### ISSUE THREAD

**Issue by hyrious** [crimx/val-i18n#2]
```js
import { I18n } from "val-i18n";

let i18n = new I18n("en", { en: { apples: "{{n}} apples" } });
console.log(i18n.t("apples", { n: 0 }));
console.log(i18n.t("apples", { n: 1 }));
```

Outputs:

```
n apples
1 apples
```

**Comment by crimx** [comment]
The `options` parameter in `t` is of type `Record<string, string>`. It was expecting `string` as values. Looks like I can support number as well.

**Comment by crimx** [comment]
I see what went wrong.

The implementaion

https://github.com/crimx/val-i18n/blob/2841bbcf20a8fed951f1a46a2ad24fee46687b1a/src/i18n.ts#L65

is different from the type

https://github.com/crimx/val-i18n/blob/2841bbcf20a8fed951f1a46a2ad24fee46687b1a/src/interface.ts#L16-L24

**Comment by crimx** [comment]
`val-i18n@0.1.4` published.
